require: rubocop-bridgetown

inherit_gem:
  rubocop-bridgetown: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7

  Exclude:
    - .gitignore
    - .rspec
    - .rubocop.yml

    - Rakefile
    - bridgetown.automation.rb
    - "*.gemspec"
    - Gemfile.lock
    - CHANGELOG.md
    - LICENSE.txt
    - README.md

    - example/**/*
    - script/**/*
    - vendor/**/*
    - spec/**/*
